pipeline {
    agent any
    
    environment {
     SEMGREP_APP_TOKEN = credentials('SEMGREP_APP_TOKEN')
    }

    stages {
        stage('semgrep scan') {
            steps { 
                echo "semgrep started"
                sh 'pwd'
                sh 'semgrep --version'
                // sh 'semgrep scan --config auto --output devsecops/semgrepscanjuiceshop_results.json --json --exclude="devsecops"'
                echo "semgrep completed"
            }
        }
        stage('push in defectdojo') {
            steps {
                echo 'Hello World'
            }
        }
    }
}
